# Generated by Django 3.0 on 2022-05-03 07:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobapp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_rounds', models.IntegerField(default=5)),
                ('round', models.IntegerField(choices=[('1', 'Round 1'), ('2', 'Round 2'), ('3', 'Round 3'), ('4', 'Round 4'), ('5', 'Round 5')], default=1)),
                ('current_status', models.IntegerField(default=-1)),
                ('email_id_of_interviewer', models.EmailField(default=None, max_length=254)),
                ('round_status', models.IntegerField(default=0)),
                ('interview_slot1', models.DateTimeField()),
                ('interview_slot2', models.DateTimeField()),
                ('interview_slot3', models.DateTimeField()),
                ('round_link', models.URLField()),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employee', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Job', to='jobapp.Job')),
                ('recruiter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Employer', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
