# Generated by Django 3.0 on 2022-05-03 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduler', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='email_id_of_interviewer',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
