# Generated by Django 3.0 on 2022-05-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interview_scheduler', '0002_auto_20220503_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_slot1',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_slot2',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='interview_slot3',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedule',
            name='round_link',
            field=models.URLField(null=True),
        ),
    ]
